version: "3.8"

services:
  htrflow:
    image: airiksarkivet/htrflow:v0.2.2-14b64fe
    platform: linux/amd64
    container_name: htrflow
    restart: unless-stopped
    volumes:
      - temp-yaml-storage:/tmp/yaml # Shared volume for temporary YAML files
      - temp-image-storage:/tmp/images # Shared volume for temporary images
      - temp-htrflow-outputs:/tmp/outputs # Shared volume for temporary outputs
      - models:/models # Shared volume for models
    tty: true # Keeps the container running for CLI use

  forsete-atr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forsete-atr
    restart: unless-stopped
    depends_on:
      - htrflow
    volumes:
      - temp-yaml-storage:/tmp/yaml # Shared volume for temporary YAML files
      - temp-image-storage:/tmp/images # Shared volume for temporary images
      - temp-htrflow-outputs:/tmp/outputs # Shared volume for temporary outputs
      - models:/models # Shared volume for models
    ports:
      - "8080:8080"
    environment:
      - API_PORT=${API_PORT}

volumes:
  temp-yaml-storage:
  temp-image-storage:
  temp-htrflow-outputs:
  models:
