DROP TABLE IF EXISTS pipelines_models;

DROP TABLE IF EXISTS pipelines;

DROP TABLE IF EXISTS models;

DROP TABLE IF EXISTS model_type;

DROP TABLE IF EXISTS outputs;

DROP TABLE IF EXISTS images;

DROP TABLE IF EXISTS users_projects;

DROP TABLE IF EXISTS projects;

DROP TABLE IF EXISTS users;
