// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/forsete-atr/v1/atr/basic-documents/": {
            "post": {
                "description": "Run ATR on image-file",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ATR"
                ],
                "summary": "ATR",
                "parameters": [
                    {
                        "type": "file",
                        "description": "png",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of line segmentation model",
                        "name": "line_segmentation_model",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of text recognition model",
                        "name": "text_recognition_model",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ATRResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/util.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forsete-atr/v1/models/": {
            "get": {
                "description": "Retrieve all active models",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Models"
                ],
                "summary": "Models",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ModelsResponse"
                        }
                    }
                }
            }
        },
        "/forsete-atr/v1/models/line-segmentation-models/": {
            "get": {
                "description": "Retrieve all active line segmentation models",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LineSegmentationModels"
                ],
                "summary": "LineSegmentationModels",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ModelsResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a line segmentation model",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LineSegmentationModels"
                ],
                "summary": "LineSegmentationModels",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the model",
                        "name": "model_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "model.pt",
                        "name": "model",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/util.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forsete-atr/v1/models/region-segmentation-models/": {
            "get": {
                "description": "Retrieve all active region segmentation models",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RegionSegmentationModels"
                ],
                "summary": "RegionSegmentationModels",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ModelsResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a region segmentation model",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RegionSegmentationModels"
                ],
                "summary": "RegionSegmentationModels",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the model",
                        "name": "model_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "model.pt",
                        "name": "model",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/util.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forsete-atr/v1/models/text-recognition-models/": {
            "get": {
                "description": "Retrieve all active text recognition models",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TextRecognitionModels"
                ],
                "summary": "TextRecognitionModels",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ModelsResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a text recognition model",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TextRecognitionModels"
                ],
                "summary": "TextRecognitionModels",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the model",
                        "name": "model_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "model.safetensors",
                        "name": "model",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "config.json",
                        "name": "config",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "generation_config.json",
                        "name": "generation_config",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "merges.txt",
                        "name": "merges",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "preprocessor_config-json",
                        "name": "preprocessor_config",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "special_tokens_map.json",
                        "name": "special_tokens_map",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "tokenizer.json",
                        "name": "tokenizer",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "tokenizer_config.json",
                        "name": "tokenizer_config",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "vocab.json",
                        "name": "vocab",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/util.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forsete-atr/v1/status/": {
            "get": {
                "description": "Retrieve status of service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status"
                ],
                "summary": "GetStatus",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Status"
                        }
                    }
                }
            },
            "head": {
                "description": "Retrieve status of service",
                "tags": [
                    "Status"
                ],
                "summary": "HeadStatus",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ATRResponse": {
            "description": "Json-Response for ATR",
            "type": "object",
            "properties": {
                "contains": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "segment": {
                                "type": "object",
                                "properties": {
                                    "bbox": {
                                        "type": "object",
                                        "properties": {
                                            "xmax": {
                                                "type": "integer"
                                            },
                                            "xmin": {
                                                "type": "integer"
                                            },
                                            "ymax": {
                                                "type": "integer"
                                            },
                                            "ymin": {
                                                "type": "integer"
                                            }
                                        }
                                    },
                                    "class_label": {
                                        "type": "string"
                                    },
                                    "data": {
                                        "type": "object"
                                    },
                                    "orig_shape": {
                                        "type": "array",
                                        "items": {
                                            "type": "integer"
                                        }
                                    },
                                    "polygon": {
                                        "type": "object",
                                        "properties": {
                                            "points": {
                                                "type": "array",
                                                "items": {
                                                    "type": "object",
                                                    "properties": {
                                                        "x": {
                                                            "type": "integer"
                                                        },
                                                        "y": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    },
                                    "score": {
                                        "type": "number"
                                    }
                                }
                            },
                            "text_result": {
                                "type": "object",
                                "properties": {
                                    "label": {
                                        "type": "string"
                                    },
                                    "scores": {
                                        "type": "array",
                                        "items": {
                                            "type": "number"
                                        }
                                    },
                                    "texts": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "file_name": {
                    "type": "string"
                },
                "image_name": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "handler.ModelsResponse": {
            "description": "Json-Response for models",
            "type": "object",
            "properties": {
                "line_segmentation_models": {
                    "type": "array",
                    "items": {}
                },
                "region_segmentation_models": {
                    "type": "array",
                    "items": {}
                },
                "text_recognition_models": {
                    "type": "array",
                    "items": {}
                }
            }
        },
        "handler.Status": {
            "description": "Json-response for Status",
            "type": "object",
            "properties": {
                "uptime": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "util.ErrorResponse": {
            "description": "Json-Response on error",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Forsete-ATR",
	Description:      "RESTful JSON-API for Automatic Text Recognition (ATR) developed as part of Bachelor Thesis \"FORSETE\" at NTNU Gjøvik.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
