name: Deploy dev

on:
  push:
    branches:
      - dev
    paths:
      - "src/**"
      - "main.go"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  TF_VAR_application_credential_id: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
  TF_VAR_application_credential_secret: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
  WORKING_DIR: "backend"
  GH_TOKEN: ${{ github.token }}

jobs:
  terraform:
    name: Deploy to OpenStack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIR }}
