name: On-push feature branch

on:
  push:
    branches-ignore:
      - main
      - test
      - dev
    paths:
      - "backend/**"
      - "src/**"
      - "main.go"
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  TF_VAR_application_credential_id: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
  TF_VAR_application_credential_secret: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
  TF_VAR_my_openstack_key_public: ${{ secrets.OS_PUBLIC_KEY }}
  GH_TOKEN: ${{ github.token }}

jobs:
  format:
    name: Format Terraform Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@master

      - name: Terraform fmt
        id: fmt
        uses: ./.github/actions/format

  validate:
    name: Validate Terraform Files
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@master

      - name: Terraform validate
        id: validate
        uses: ./.github/actions/validate
        with:
          working_dir: "backend"

  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@master

      - name: Go test
        id: go-test
        uses: ./.github/actions/test_go
