name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      working_dir:
        description: "Working directory"
        required: true
        default: "backend"

env:
  TF_VAR_application_credential_id: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
  TF_VAR_application_credential_secret: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
  TF_VAR_my_openstack_key_public: ${{ secrets.OS_PUBLIC_KEY }}

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: Destroy OpenStack resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Terraform
        id: setup-terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ${{ env.WORKING_DIR }}
